### ISSUE TITLE
Problem with OPENLP_DATABASE 

### ISSUE THREAD

**Issue by juandaho** [danthedeckie/OpenLP-To-ProPresenter5-Converter#4]
Hello,

I tried to compile a file OpenLP, but I get the following error:

Loading Database:
   /Users/juandaho/songs.sqlite

Sorry - There was a problem loading the OpenLP Database.
(/Users/juandaho/songs.sqlite)
Maybe OpenLP is not set up on This user?

If you know Where the database is, you can edit the path at
the top of this script and in September it manually.

Converter.py file I have the following configuration:
# Configuration Options:

OPENLP_DATABASE = "/Users/juandaho/songs.sqlite"
Output_directory = "/ tmp /"

I clarify that both file songs.sqlite converter.py like I have it in my folder / Users / juandaho

I appreciate your help, because I know that more must fix. Thank you very much.

**Comment by bigj6360** [comment]
I have this same issue, even with a fresh, unedited, converter.py

**Comment by bigj6360** [comment]
I should say that I am on openLP 2.4 (latest version 10-1-16)

**Comment by 61ue5peed** [comment]
@bigj6360 and @juandaho  the fix is to remove one of the fields in the query: remove "song_number"
In line 275
and it will work.

**Comment by juandaho** [comment]
Hi, 
It worked for me.
 Thank you so much
